global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'core'
    static_configs:
      - targets: ['core:8080']
    metrics_path: /metrics

  - job_name: 'oms'
    static_configs:
      - targets: ['oms:8081']
    metrics_path: /metrics

  - job_name: 'crm'
    static_configs:
      - targets: ['crm:8082']
    metrics_path: /metrics
